### ISSUE TITLE
Import failed

### ISSUE THREAD

**Issue by freeAhao** [ltdrdata/ComfyUI-Workflow-Component#18]
```
Traceback (most recent call last):
  File "/home/ahao/Documents/ComfyUI/nodes.py", line 1688, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ahao/Documents/ComfyUI/custom_nodes/ComfyUI-Workflow-Component/__init__.py", line 47, in <module>
    import workflow_component.custom_server
  File "/home/ahao/Documents/ComfyUI/custom_nodes/ComfyUI-Workflow-Component/workflow_component/custom_server.py", line 42, in <module>
    server.PromptServer.instance.add_on_prompt_handler(onprompt)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PromptServer' object has no attribute 'add_on_prompt_handler'

Cannot import /home/ahao/Documents/ComfyUI/custom_nodes/ComfyUI-Workflow-Component module for custom nodes: 'PromptServer' object has no attribute 'add_on_prompt_handler'

Import times for custom nodes:
   0.0 seconds: /home/ahao/Documents/ComfyUI/custom_nodes/failfast-comfyui-extensions
   0.0 seconds: /home/ahao/Documents/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /home/ahao/Documents/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.0 seconds: /home/ahao/Documents/ComfyUI/custom_nodes/ComfyUI-WD14-Tagger
   0.0 seconds: /home/ahao/Documents/ComfyUI/custom_nodes/bilbox-comfyui
   0.0 seconds: /home/ahao/Documents/ComfyUI/custom_nodes/ComfyUI-Manager
   0.1 seconds (IMPORT FAILED): /home/ahao/Documents/ComfyUI/custom_nodes/ComfyUI-Workflow-Component
   0.4 seconds: /home/ahao/Documents/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.7 seconds: /home/ahao/Documents/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
```

**Comment by ltdrdata** [comment]
Update ComfyUI to latest version.
