### ISSUE TITLE
run Image Refiner,  after drawing mask and Regenerate, no processing, and cmd show:

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Workflow-Component#23]
run Image Refiner,  after drawing mask and Regenerate, no processing, and cmd show:
(by the way , comfyui and all your extension is lastest, and "fetch updates" in the manager, still no work)

model_type EPS
adm 0
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.text_projection', 'cond_stage_model.logit_scale'}
left over keys: dict_keys(['cond_stage_model.transformer.text_model.embeddings.position_ids'])
loading new
[DBG] work: 17 (MaskToSEGS) / worklist: []
# of Detected SEGS: 1
[DBG] work: 32 (DetailerForEachTestPipe) / worklist: []
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 159, in exception_helper
    task()
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 372, in task
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 88, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 81, in map_node_over_list
    results.append(getattr(obj, func)(**params))
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1049, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 204, in do_detail
    enhanced_pil, cnet_pil = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 166, in enhance_detail
    if len(noise_mask.shape) == 3:
AttributeError: 'NoneType' object has no attribute 'shape'

An error occurred in the 'DetailerForEachDebugPipe'(id=32) node within the component '## ## mask-detailer.ir [0a5d50]'(id=-1).
ERROR MESSAGE: 'NoneType' object has no attribute 'shape'

Prompt executed in 0.04 seconds
Error handling request
Traceback (most recent call last):
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "F:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 69, in imagerefiner_generate
    result = ir.generate(base_pil.convert('RGB'), mask_pil, prompt_data)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\imagerefiner.py", line 175, in generate
    output_data, _ = ee.get_output_data(class_def(), input_data_all)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 88, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 81, in map_node_over_list
    results.append(getattr(obj, func)(**params))
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 259, in doit
    return workflow_execution.execute(component_name, prompt, workflow,
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\workflow_execution.py", line 224, in execute
    raise Exception(msg)
Exception:
------------------------
Component internal error on [-1]:DetailerForEachDebugPipe
Error:'NoneType' object has no attribute 'shape'
Traceback:
&nbsp;&nbsp;&nbsp;  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 159, in exception_helper
    task()
&nbsp;&nbsp;&nbsp;  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 372, in task
    output_data, output_ui = get_output_data(obj, input_data_all)
&nbsp;&nbsp;&nbsp;  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 88, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
&nbsp;&nbsp;&nbsp;  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\execution_experimental.py", line 81, in map_node_over_list
    results.append(getattr(obj, func)(**params))
&nbsp;&nbsp;&nbsp;  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1049, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
&nbsp;&nbsp;&nbsp;  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 204, in do_detail
    enhanced_pil, cnet_pil = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
&nbsp;&nbsp;&nbsp;  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 166, in enhance_detail
    if len(noise_mask.shape) == 3:

------------------------

**Comment by ltdrdata** [comment]
This issue is occured when `noise_mask` is false.
This is fixed on latest version of `Impact Pack`.

**Comment by xueqing0622** [comment]
I update to the latest version of Impact Pack. still same error

**Comment by ltdrdata** [comment]
> I update to the latest version of Impact Pack. still same error

Show me the startup log.
The version should be V4.16.2

**Comment by xueqing0622** [comment]
I update all the extension of yours and comfyui
and disable nestnode, it works!
Strange,  it doesn't show up anything on startup before,  why it conflict with other extension,

**Comment by ltdrdata** [comment]
> I update all the extension of yours and comfyui
> and disable nestnode, it works!
> Strange, does it conflict with other plugins, but it doesn't show up on startup!

This is tough time for custom nides developer.

**Comment by xueqing0622** [comment]
https://github.com/ssitu/ComfyUI_NestedNodeBuilder/issues/16#issuecomment-1750900355
It appear other bug before, need to change inspire pack seed.js

**Comment by ltdrdata** [comment]
> [ssitu/ComfyUI_NestedNodeBuilder#16 (comment)](https://github.com/ssitu/ComfyUI_NestedNodeBuilder/issues/16#issuecomment-1750900355) It appear other bug before, need to change inspire pack seed.js

This is fixed and working. 
However, Within nested internal nodes, seeds are actually applied and generation takes place, but there is a limitation where the seed of the outermost node does not visually update.
