### ISSUE TITLE
Missing nodes

### ISSUE THREAD

**Issue by maxwelllord** [ltdrdata/ComfyUI-Workflow-Component#3]
I'd love to try this but i'm getting this error after installing.

I'm using the standalone Comfy build, Python 3.10, Windows 10

`[Workflow-Component] '## img-ksample-latent.component-tiled [7146f6]' is broken. Maybe there are missing nodes. (INFO: 'BNK_TiledKSampler')
Traceback (most recent call last):
  File "E:\Comfy\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 174, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map)
  File "E:\Comfy\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 320, in build_input_types
    node_input_types = comfy_nodes.NODE_CLASS_MAPPINGS[node_type].INPUT_TYPES()
KeyError: 'BNK_TiledKSampler'
[Workflow-Component] '## sdxl-ksample [1743ab]' is broken. Maybe there are missing nodes. (INFO: 'Multiply')
Traceback (most recent call last):
  File "E:\Comfy\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 174, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map)
  File "E:\Comfy\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 320, in build_input_types
    node_input_types = comfy_nodes.NODE_CLASS_MAPPINGS[node_type].INPUT_TYPES()
KeyError: 'Multiply'
[Workflow-Component] '## 2obj [a9bc98]' is broken. Maybe there are missing nodes. (INFO: 'Integer')
Traceback (most recent call last):
  File "E:\Comfy\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 174, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map)
  File "E:\Comfy\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 320, in build_input_types
    node_input_types = comfy_nodes.NODE_CLASS_MAPPINGS[node_type].INPUT_TYPES()
KeyError: 'Integer'`

**Comment by ltdrdata** [comment]
Several built-in components relies on custom nodes. 
And the above message shows 'BNK_TiledKSampler' is missing.
( https://github.com/BlenderNeko/ComfyUI_TiledKSampler )

You can install through ComfyUI-Manager's ```Install Missing Custom Nodes```.

But if you don't use that specific component. You can skip it. It won't affect to other components.

**Comment by maxwelllord** [comment]
Awesome that seems to have fixed it
