### ISSUE TITLE
Not sure if my fault or bug.

### ISSUE THREAD

**Issue by Reaper176** [ltdrdata/ComfyUI-Workflow-Component#34]
So when attempting to use the in-paint "and at no other time" i get this error. 

```
Error handling request
Traceback (most recent call last):
  File "/home/john/.local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.local/lib/python3.11/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/.local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/server.py", line 41, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/custom_nodes/ComfyUI-Workflow-Component/image_refiner/custom_server.py", line 69, in imagerefiner_generate
    result = ir.generate(base_pil.convert('RGB'), mask_pil, prompt_data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/custom_nodes/ComfyUI-Workflow-Component/image_refiner/imagerefiner.py", line 174, in generate
    input_data_all = prepare_input(class_def, merged_pil, mask_pil, prompt_data)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/custom_nodes/ComfyUI-Workflow-Component/image_refiner/imagerefiner.py", line 94, in prepare_input
    model, clip, vae = load_checkpoint(v['checkpoint'])
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/custom_nodes/ComfyUI-Workflow-Component/image_refiner/imagerefiner.py", line 38, in load_checkpoint
    model, clip, vae = comfy_nodes.CheckpointLoaderSimple().load_checkpoint(ckpt_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/nodes.py", line 541, in load_checkpoint
    out = comfy.sd.load_checkpoint_guess_config(ckpt_path, output_vae=True, output_clip=True, embedding_directory=folder_paths.get_folder_paths("embeddings"))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/comfy/sd.py", line 535, in load_checkpoint_guess_config
    clip = CLIP(clip_target, embedding_directory=embedding_directory)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/comfy/sd.py", line 103, in __init__
    self.cond_stage_model = clip(**(params))
                            ^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/comfy/sd1_clip.py", line 507, in __init__
    setattr(self, self.clip, clip_model(device=device, dtype=dtype, **kwargs))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/comfy/sd1_clip.py", line 81, in __init__
    self.transformer = model_class(config, dtype, device, comfy.ops.manual_cast)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/john/Applications/temp/ComfyUI-AAA-112/comfy/clip_model.py", line 124, in __init__
    self.text_projection.weight.copy_(torch.eye(embed_dim))
RuntimeError: a leaf Variable that requires grad is being used in an in-place operation.
```
I hope this means something to you if its a bug, and if its my fault instead of a bug it would be cool if some one could tell me whats happening and how i broke it XD <3.

**Comment by ltdrdata** [comment]
It is recommended to start by constructing a workflow with components only and testing it independently, without using ImageRefiner initially.

**Comment by DreikaEru** [comment]
Same error. Probably a problem with python_embeded. Please download the ComfyUI_windows_portable assembly with the plugin. For example, on https://mega.io/, if it doesn’t fit on github.
