### ISSUE TITLE
first time installation bug

### ISSUE THREAD

**Issue by waldolin** [ltdrdata/ComfyUI-Workflow-Component#39]
FETCH DATA from: D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Manager\extension-node-map.json
[Workflow-Component] '## img-ksample-latent.component-tiled [77a7ed]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "BNK_TiledKSampler" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "BNK_TiledKSampler" node is not installed. Please install that node through ComfyUI-Mananger. ###
[Workflow-Component] '## sdxl-ksample [3c7e70]' is broken. Maybe there are missing nodes. (INFO: ### [ERROR] "Multiply" node is not installed. Please install that node through ComfyUI-Mananger. ###)
Traceback (most recent call last):
  File "D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 209, in get_input_types_dynamic
    build_input_types(i, input_mapping, input_types, node, node_config_map, spec_map)
  File "D:\ComfyUI-Zluda\custom_nodes\ComfyUI-Workflow-Component\workflow_component\component_loader.py", line 357, in build_input_types
    raise Exception(errmsg)
Exception: ### [ERROR] "Multiply" node is not installed. Please install that node through ComfyUI-Mananger. ###

**Comment by bitshifter52** [comment]
I'm receiving the same error message.

**Comment by ltdrdata** [comment]
Literally, you have not installed custom nodes.
You need to install them via ComfyUI-Manager.
