### ISSUE TITLE
Conflicts with ComfyUI-Allor

### ISSUE THREAD

**Issue by rickcx** [ltdrdata/ComfyUI-Workflow-Component#7]
After installing ComfyUI-Workflow-Component, the following error occurs.

Traceback (most recent call last):
  File "/home/bob/ComfyUI/nodes.py", line 1516, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI-Allor/__init__.py", line 8, in <module>
    loader.setup_override()
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI-Allor/Loader.py", line 51, in setup_override
    override_nodes_len += override(lambda item: not item[1].CATEGORY.startswith("image/postprocessing"))
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI-Allor/Loader.py", line 44, in override
    nodes.NODE_CLASS_MAPPINGS = dict(
  File "/home/bob/ComfyUI/custom_nodes/ComfyUI-Allor/Loader.py", line 51, in <lambda>
    override_nodes_len += override(lambda item: not item[1].CATEGORY.startswith("image/postprocessing"))
AttributeError: type object 'ExecutionSwitch' has no attribute 'CATEGORY'

Cannot import /home/bob/ComfyUI/custom_nodes/ComfyUI-Allor module for custom nodes: type object 'ExecutionSwitch' has no attribute 'CATEGORY'

0.0 seconds (IMPORT FAILED): /home/bob/ComfyUI/custom_nodes/ComfyUI-Allor

After I removed ComfyUI-Workflow-Component, the error no longer occurs and ComfyUI-Allor can be loaded correctly.

**Comment by ltdrdata** [comment]
patched on 0.39.6

**Comment by rickcx** [comment]
It's working now. Thanks ! Your custom nodes are awsome ！
